Principal Components
====================

We will use the `USArrests   data (which is in R)

```{r}
dimnames(USArrests)
apply(USArrests,2,mean)
apply(USArrests,2, var)
```

Need to standardize to unit variance

```{r}
pca.out=prcomp(USArrests,scale=TRUE)
pca.out
names(pca.out)
biplot(pca.out,scale=0,cex=0.6)
```

K-means-clustering
==================
```{r}
set.seed(101)
x=matrix(rnorm(100*2),100,2)
xmean=matrix(rnorm(8,sd=4),4,2)
which=sample(1:4,100,replace=TRUE)
x=x+xmean[which,]
plot(x,col=which,pch=19)

km.out=kmeans(x,4,nstart=15)
km.out
plot(x,col=km.out$cluster,cex=2,pch=1,lwd=2)
points(x,col=which,pch=19)
points(x,col=c(4,3,2,1)[which],pch=19)
```

Hierarchical Clustering
=======================

```{r}
hc.complete=hclust(dist(x),method='complete')
plot(hc.complete)
hc.single<-hclust(dist(x),method='single')
plot(hc.single) #tends to find long strung out clusters because it is looking at closest point
hc.average<-hclust(dist(x),method='average')
plot(hc.average)


hc.cut=cutree(hc.complete,4)
table(hc.cut,which)
table(hc.cut,km.out$cluster)

plot(hc.complete,labels=which,cex=0.6)
```